### ISSUE TITLE
Use [[nodiscard]] for classes & constructors

### ISSUE THREAD

**Issue by martinus** [offa/scope-guard#169]
Hi, first thanks a lot for this work! I've been using scope_exit in a project, and we recently had a bug because this works:

```cpp
sr::scope_exit([] { /* ... */ });
```

It would help to mark the whole classes as `[[nodiscard]]`, and add it to the constructors. Adding to the constructor currently produces the warning `-Wattributes` on g++ which has to be disabled

**Comment by offa** [comment]
Thanks for your report!

[P0052](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0052r10.pdf) doesn't mention the `[[nodiscard]]`, nor does the [Library Fundamental TS v3](https://cplusplus.github.io/fundamentals-ts/v3.html#scopeguard). But from your experience it sounds reasonable. 

I have pushed a branch, containing the attribute, for testing. Not only do the results differ between gcc and clang on my system, but also between their versions (see [CI build](https://travis-ci.org/github/offa/scope-guard/builds/708811506); failure is intentional):

- **GCC 10:** unused warning on `unique_resource` only
- **GCC 7-9:** ctor related compilation error
- **Clang 10:** Ok (the only one…)
- **Clang 5-9:** ctor related compilation error

**Comment by martinus** [comment]
No, I've not reported this to anybody yet. Do you know who best to contact, and where?

**Comment by offa** [comment]
The best contact should be the [ISO C++ mailing list](https://lists.isocpp.org/mailman/listinfo.cgi/std-proposals) I guess. There are some more infos [here](https://isocpp.org/std/submit-issue).

**Comment by offa** [comment]
It seems the `[[nodiscard]]` on constructors is a defect: https://en.cppreference.com/w/cpp/language/attributes/nodiscard, related paper: [**P1771**](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1771r1.pdf).

**Comment by martinus** [comment]
ah, that's interesting, P1771R1 talks specifically about scope_exit

It seems with that with `__has_cpp_attribute(nodiscard) >= 201907` it's possible to check if `[[noexcept]]` for constructors are supported: https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations#attribute-feature-test-macros

**Comment by offa** [comment]
You mean `[[noexcept]]`? Unfortunately, only clang 10 seems to get it right at the moment.

**Comment by martinus** [comment]
It seems to work for me with g++10, at least a simple example. MSVC 19.24 works too, but it seems it doesn't have the right `__has_cpp_attribute(nodiscard)` version:

https://godbolt.org/z/bvj4zM

**Comment by offa** [comment]
As `[[nodiscard]]` should work on ordinary functions on all compiler, maybe it's viable to create some free factory functions to workaround the issue? Earlier version of the proposal included some make-functions, which got replaced by deduction guides eventually.

**Comment by offa** [comment]
@martinus are there any news?

**Comment by martinus** [comment]
Hi! I didn't follow this any more, but I saw that Peter Sommerlad, the one who wrote P0052R10 – Generic Scope Guard and RAII Wrapper for the Standard Library, also wrote the proposal "P1771R1 - [[nodiscard]] for constructors".

If I understand this correctly, [[nodiscard]] for constructors is adopted for C++20: https://github.com/cplusplus/papers/issues/526 So in future this should work.

The unique_resource though seems to not make it into C++20: https://github.com/cplusplus/papers/issues/196 I have no idea though what "#278 will continue toward LFTS3." means. Also, here is Sommerlad's scope implementation: https://github.com/PeterSommerlad/scope17

**Comment by offa** [comment]
Thanks for your update, so I can close here for now. Once C++20 is out (and supported by compilers), I'll can add the `[[nodiscard]]`.
