### ISSUE TITLE
Typo in conanfile.py

### ISSUE THREAD

**Issue by jamesiain** [offa/scope-guard#219]
On line 13 of conanfile.py (in the root directory of the project), there is a single character mistake in the URL which makes "offa" part of the website name instead of a subdirectory within the github.com website.

Here is how it is currently written:
  url = "https://github.com.offa/scope-guard"

I believe that the correct line should be:
  url = "https://github.com/offa/scope-guard"

**Comment by offa** [comment]
:see_no_evil: Nice catch, thanks! Fix is on the way …
